pagina_web/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # Página inicial
    url(r'^$', views.index, name='index'),
    url(r'^visualizar/$', views.visualizar, name = 'visualizar'),
    url(r'^incluir/$', views.incluir, name = 'incluir'),
    url(r'deletar/(?P<cliente_id>\d+)/$', views.deletar, name='deletar'),
    url(r'editar/(?P<cliente_id>\d+)/$', views.editar, name='editar'),
    url(r'^pesquisar/$', views.pesquisar, name = 'pesquisar'),
]

web/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('pagina_web.urls', namespace='pagina_web')),
]

pagina_web/models.py
from django.db import models

# Create your models here.

pagina_web/forms.py
from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator


class ClienteForm(forms.Form):

    nome = forms.CharField(label='Nome', required=True)
    sobrenome = forms.CharField(label='Sobrenome', required=True)
    cpf = forms.CharField(label='CPF', required=True)
    opcoes = (('0', 'Masculino'),('1', 'Feminino'))
    sexo = forms.ChoiceField(widget=forms.RadioSelect(),choices=opcoes)
    idade = forms.IntegerField(
        validators=[MaxValueValidator(130),
                    MinValueValidator(0)
                    ]
    )

    def __init__(self, *args, **kwargs):
        super(ClienteForm, self).__init__(*args, **kwargs)
        self.fields['nome'].widget.attrs['class'] = 'form-control form-control-sm'
        self.fields['nome'].widget.attrs['id'] = 'id_nome_cliente'
        self.fields['nome'].widget.attrs['placeholder'] = 'Digite o nome'

        self.fields['sobrenome'].widget.attrs['class'] = 'form-control form-control-sm'
        self.fields['sobrenome'].widget.attrs['id'] = 'id_sobrenome_cliente'
        self.fields['sobrenome'].widget.attrs['placeholder'] = 'Digite o sobrenome'

        self.fields['cpf'].widget.attrs['class'] = 'form-control form-control-sm'
        self.fields['cpf'].widget.attrs['id'] = 'id_sobrenome_cliente'
        self.fields['cpf'].widget.attrs['placeholder'] = '___.___.___-__'

        self.fields['sexo'].widget.attrs['class'] = 'form-check-input'
        self.fields['sexo'].widget.attrs['id'] = 'id_sexo_cliente'

        self.fields['idade'].widget.attrs['class'] = 'form-control form-control-sm'
        self.fields['idade'].widget.attrs['id'] = 'id_idade_cliente'
        self.fields['idade'].widget.attrs['placeholder'] = 'Informe a idade'



class TermoPesquisa(forms.Form):

    pesquisa = forms.CharField(label='', required=True)

    def __init__(self, *args, **kwargs):
        super(TermoPesquisa, self).__init__(*args, **kwargs)
        self.fields['pesquisa'].widget.attrs['class'] = 'form-control form-control-sm w-50'
        self.fields['pesquisa'].widget.attrs['id'] = 'id_pesquisa_form'
        self.fields['pesquisa'].widget.attrs['placeholder'] = 'Procure...'

pagina_web/views.py
from django.shortcuts import render
from .forms import ClienteForm
from .forms import TermoPesquisa
import requests
import json

# Create your views here.
def index(request):
    return render(request, 'pagina_web/index.html')

def visualizar(request):
    clientes = requests.get('http://gui-webservice.herokuapp.com/clientes-api/').json()
    context = {
        'clientes' : clientes,
    }
    return render(request, 'pagina_web/visualizar.html', context)

def pesquisar(request):

    if request.method == 'POST':
        pesquisar_form = TermoPesquisa(request.POST)
        if pesquisar_form.is_valid():
            pesquisa = pesquisar_form.cleaned_data['pesquisa']
            dicio = {'pesquisa' : pesquisa}
            print(pesquisa)
            print(dicio)
            json.dumps(dicio)
            r = requests.post('http://gui-webservice.herokuapp.com/clientes-api/pesquisar/', data=dicio).json()
            print(r)
            clientes = r
            pesquisado = True
            context = {
                'pesquisa': pesquisa,
                'pesquisar_form' : pesquisar_form,
                'clientes' : clientes,
                'pesquisado' : pesquisado
            }
            return render(request, 'pagina_web/pesquisar.html', context)
        else:
            pesquisar_form = TermoPesquisa()
            context = {
                'pesquisar_form': pesquisar_form,
            }
            return render(request, 'pagina_web/pesquisar.html', context)

    else:
        pesquisar_form = TermoPesquisa()
        context = {
            'pesquisar_form': pesquisar_form,
        }
        return render(request, 'pagina_web/pesquisar.html', context)

def incluir(request):
    if request.method == 'GET':
        incluir_form = ClienteForm()
        context = {
            'incluir_form' : incluir_form,
        }
        return render(request, 'pagina_web/incluir.html', context)

    elif request.method == 'POST':

        sucesso = False
        incluir_form = ClienteForm(request.POST)
        if incluir_form.is_valid():
            nome = incluir_form.cleaned_data['nome']
            sobrenome = incluir_form.cleaned_data['sobrenome']
            cpf = incluir_form.cleaned_data['cpf']
            sexo = incluir_form.cleaned_data['sexo']
            idade = incluir_form.cleaned_data['idade']
            dicio = {'nome':nome, 'sobrenome':sobrenome, 'cpf':cpf, 'sexo':sexo, 'idade':idade}
            json.dumps(dicio)
            r = requests.post('http://gui-webservice.herokuapp.com/clientes-api/', data=dicio)
            incluir_form = ClienteForm()
            sucesso = True
            context = {'sucesso' : sucesso, 'incluir_form' : incluir_form}
            return render(request, 'pagina_web/incluir.html', context)
        else:
            erro = True
            context = {'erro': erro, 'incluir_form': incluir_form}
            return render(request, 'pagina_web/incluir.html', context)


def deletar(request, cliente_id):
    r = requests.delete('http://gui-webservice.herokuapp.com/clientes-api/' + cliente_id)
    clientes = requests.get('http://gui-webservice.herokuapp.com/clientes-api/').json()
    context = {
        'clientes': clientes,
    }
    return render(request, 'pagina_web/visualizar.html', context)

def editar(request, cliente_id):
    r = requests.get('http://gui-webservice.herokuapp.com/clientes-api/' + cliente_id).json()
    if request.method == 'GET':
        incluir_form = ClienteForm(r)
        context = {'incluir_form' : incluir_form}
        return render(request, 'pagina_web/editar.html', context)

    elif request.method == 'POST':
        editar_form = ClienteForm(request.POST)
        if editar_form.is_valid():
            form = editar_form.cleaned_data
            print(form)
            req = requests.post('http://gui-webservice.herokuapp.com/clientes-api' + '/' + cliente_id + '/', data=form)
            print(req.text)
            editar_form = ClienteForm(request.POST)
            sucesso = True
            context = {'sucesso': sucesso, 'incluir_form': editar_form}
            return render(request, 'pagina_web/editar.html', context)

        else:
            editar_form = ClienteForm(request.POST)
            erro = True
            context = {'erro': erro, 'editar_form': editar_form}
            return render(request, 'pagina_web/editar.html', context)

pagina_web/templates/pagina_web/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Requests</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'pagina_web/css/bootstrap.css' %}">
		<link rel="stylesheet" href="{% static 'pagina_web/css/estilo.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary">

      <button type="button" class="navbar-toggler" data-toggle="collapse"
      data-target="#navbarSite">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSite">
        <div class="container">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a href="{% url 'pagina_web:index' %}" class="nav-link">Inicio</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'pagina_web:visualizar' %}" class="nav-link">Visualizar</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'pagina_web:incluir' %}" class="nav-link">Incluir</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'pagina_web:pesquisar' %}" class="nav-link">Pesquisar</a>
            </li>
          </ul>
          </div>
      </div>

    </nav>
    {% block content %}
    {% endblock %}

    <!-- FOOTER -->
    <hr class="mt-5">
    <footer class="container">
      <div class="row">
        <div class="col-6">
          <p class="float-right pr-0"></p>
          <p>Copyright 2018. &copy;. Todos os direitos reservados.
        </div>
        <div class="col-6 pl-0">
          Desenvolvido por
          <a href="#">
            Guilherme Luis
          </a> &middot;
        </div>
        </p>
      </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

pagina_web/templates/pagina_web/editar.html
{% extends "pagina_web/base.html" %}
{% block content %}

<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Editar cliente</h1>
  </div>
</div>

<div class="container">
    {% if sucesso %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        Cliente editado com sucesso
    </div>
    {% endif %}
    {% if erro %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        Preencha todos os campos corretamente
    </div>
    {% endif %}

    {% if incluir_form %}
    <form method="POST">
        {% csrf_token %}
        {{ incluir_form.as_p }}
        <button type="submit" class="btn btn-sm btn-outline-success">Enviar</button>
    </form>
    {% else %}
    <form method="POST">
        {% csrf_token %}
        {{ editar_form.as_p }}
        <button type="submit" class="btn btn-sm btn-outline-success">Enviar</button>
    </form>
    {% endif %}
</div>
{% endblock %}

pagina_web/templates/pagina_web/incluir.html
{% extends "pagina_web/base.html" %}
{% block content %}

<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Incluir novo cliente</h1>
  </div>
</div>

<div class="container">
    {% if sucesso %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        Cliente incluído com sucesso
    </div>
    {% endif %}
    {% if erro %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        Preencha todos os campos corretamente
    </div>
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        {{ incluir_form.as_p }}
        <button type="submit" class="btn btn-sm btn-outline-success">Enviar</button>
    </form>
</div>
{% endblock %}

pagina_web/templates/pagina_web/index.html
{% extends "pagina_web/base.html" %}
{% block content %}

<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Olá, Mundo!</h1>
  </div>
</div>

{% endblock %}

pagina_web/templates/pagina_web/pesquisar.html
{% extends "pagina_web/base.html" %}
{% block content %}

<div class="jumbotron">
  <div class="container">
    <h1 class="display-3 mb-5">Pesquisar Clientes</h1>
    <form method="POST">
        {% csrf_token %}
        {{ pesquisar_form.as_p }}
        <button type="submit" class="btn btn-sm btn-outline-success">Buscar</button>
    </form>
  </div>
</div>
<div class="container my-5">
    {% if sucesso %}
    <div class="alert alert-success">
        Mensagem enviada com sucesso
    </div>
    {% endif %}
</div>

<div class="container">
  {% if clientes %}
  <table class="table table-hover">
    <thead class="thead-dark initialism" align="center">
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Sexo</th>
        <th scope="col">Idade</th>
        <th scope="col">Editar</th>
        <th scope="col">Deletar</th>
      </tr>
    </thead>
      <tbody align="center">
      {% for i in clientes %}
      <tr>
        <td>
          <span>{{i.nome}}</span>

        </td>
        <td>{{i.sexo}}</td>
        <td>{{i.idade}}</td>
        <td><a href="{% url 'pagina_web:editar' i.id %}">Editar</a></td>
        <td><a href="{% url 'pagina_web:deletar' i.id %}">x</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
    {% if pesquisado %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        Nenhum cliente encontrado
    </div>
    {% endif %}
  {% endif %}
</div>

{% endblock %}

pagina_web/templates/pagina_web/visualizar.html
{% extends "pagina_web/base.html" %}
{% block content %}

<div class="jumbotron">
  <div class="container">
    <h1 class="display-3 mb-5">Visualizar Clientes</h1>
  </div>
</div>


<div class="container">
  <table class="table table-hover">
    <thead class="thead-dark initialism" align="center">
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Sexo</th>
        <th scope="col">Idade</th>
        <th scope="col">Editar</th>
        <th scope="col">Deletar</th>
      </tr>
    </thead>
    <tbody align="center">
      {% for i in clientes %}
      <tr>
        <td>
          <span>{{i.nome}}</a>

        </td>
        <td>{{i.sexo}}</td>
        <td>{{i.idade}}</td>
        <td><a href="{% url 'pagina_web:editar' i.id %}">Editar</a></td>
        <td><a href="{% url 'pagina_web:deletar' i.id %}">x</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}